"""
Django settings for vibespot project.
Generated by 'django-admin startproject' using Django 2.0.
For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/
For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os


#Environment variables
import dotenv
from dotenv import load_dotenv
dotenv.load_dotenv()



# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
load_dotenv(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/
from django.conf import settings
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '32s-6zg^c7(#c^z&d=z*&f3366-^4wg%$s)1y2up)w253kos#cyfherk'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['167.99.110.73', 'localhost']


# Application definition

INSTALLED_APPS = [
    
   
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'vibe_user',
    'dashboard',
    'django_extensions',
    # 'react',
    'corsheaders',
]


AUTH_USER_MODEL ='vibe_user.User'

CORS_ORIGIN_ALLOW_ALL=True
CORS_ALLOW_CREDENTIALS=True
CORS_ORIGIN_WHITELIST=(
        'localhost:3000',
        '127.0.0.1:3000',
        )

EMAIL_BACKEND = os.getenv("EMAIL_BACKEND")
SENDGRID_API_KEY = os.getenv("SEND_GRID_API_KEY")
DEFAULT_EMAIL_BCC=""
DEFAULT_EMAIL_FROM = os.getenv("DEFAULT_FROM_EMAIL")


REST_FRAMEWORK={
    'DEFAULT_AUTHENTICATION_CLASSES':(
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES':(
        'rest_framework.permissions.IsAuthenticated',
    ),
    'EXCEPTION_HANDLER': 'vibe_user.exceptions.core_exception_handler',
    'NON_FIELD_ERRORS_KEY': 'error',
}
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'vibespot.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vibespot.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

# 




# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME':  os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }


# DATABASES = {

#        'default': {    
#            'ENGINE': 'django.db.backends.postgresql_psycopg2',
#            'NAME': 'admincatdatabase',
#            'USER': 'vibespot',
#            'PASSWORD': 'Adm1nC@t',
#            'PORT': '',
#            'HOST':'localhost',
#            }
#        }


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'vibespotdatabase',
        'USER': 'vibespot',
        'PASSWORD': 'Vibespot@Intemporel2018',
        'HOST': 'localhost',
        'PORT': '',    
        }
}



# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REACT_APP = ''

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/
# STATIC_ROOT = 'staticfiles'

# STATICFILES_DIRS = (
#     os.path.join(os.path.join(BASE_DIR, 'build'), 'static'),
# )

# STATIC_URL = '/static/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'static/')

# STATIC_URL='/static/'
# MEDIA_ROOT=os.path.join(BASE_DIR, 'static/')
# MEDIA_URL='/media/'
# MEDIA_ROOT=os.path.join(BASE_DIR, 'media/')

STATIC_ROOT = os.path.join(BASE_DIR, 'static')

STATICFILES_DIRS = (
    os.path.join(os.path.join(BASE_DIR, 'build'), 'static'),
)

STATIC_URL = '/static/'