# Generated by Django 2.0 on 2018-12-06 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibe_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membertype',
            name='long_description',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
